### ISSUE TITLE
So... did it work?

### ISSUE THREAD

**Issue by gypsydave5** [jhunt/cl-buildpack#1]
Really intrigued - did this work at all?

**Comment by arademaker** [comment]
I would like to propose a simple demo... imagine a hello world app using Hunchentoot and using this buildpack... Hi @jhunt , that would help me a lot. I do have already my app in https://github.com/own-pt/cl-wnbrowser. It is a 100% CL webapp using ElasticSearch as backend. ES is provided as a service in the IBM Cloud. So the only think that I really need now is to understand how to actually use this buildback to deploy the CL app.

**Comment by jhunt** [comment]
I actually used this for SHOUT! https://github.com/jhunt/shout

**Comment by arademaker** [comment]
Hum, sorry, I failed to see in shout repo how this buildpack is being used. Moreover, I am now with another error. It seems that SBCL 2.1.4 does not run on the cflinuxfs3  stack, provided by the Cloud Foundry at IBM Cloud.

**Comment by arademaker** [comment]
No solution?
